/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import core.BuildingTools;
import core.GameManager;
import core.ResourceManager;
import javax.swing.JOptionPane;

import buildings.Farm;

/**
 *
 * @author Fer
 */
public class FarmMelhoria extends javax.swing.JFrame {
    GameManager gameData;
    /**
     * Creates new form FarmUso
     */
    public FarmMelhoria(GameManager gameData) {
        this.setResizable(false);
        //this.setLocationRelativeTo(null);
        this.gameData = gameData;
        initComponents();
        
        labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage = new javax.swing.JLabel();
        labelFARM = new javax.swing.JLabel();
        labelFP = new javax.swing.JLabel();
        labelSF = new javax.swing.JLabel();
        labelCF = new javax.swing.JLabel();
        labelGP = new javax.swing.JLabel();
        btnFoodProduction = new javax.swing.JButton();
        btnSeedFertilizer = new javax.swing.JButton();
        btnCocoFertilizer = new javax.swing.JButton();
        btnGreatProduction = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        labelCreativityDONTEDIT = new javax.swing.JLabel();
        labelCreativity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FarmBig.png"))); // NOI18N

        labelFARM.setFont(new java.awt.Font("Bangla Sangam MN", 0, 24)); // NOI18N
        labelFARM.setText("ROÇA");

        labelFP.setText("Produção de Comida:");

        labelSF.setText("Fertilizador de Semente:");

        labelCF.setText("Fertilizador de Coco:");

        labelGP.setText("Grande Produção:");

        btnFoodProduction.setText("Locked: 30");
        btnFoodProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodProductionActionPerformed(evt);
            }
        });

        btnSeedFertilizer.setText("Locked: 30");

        btnCocoFertilizer.setText("Locked: 30");

        btnGreatProduction.setText("Locked: 60");

        btnSair.setText("Close");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        labelCreativityDONTEDIT.setText("Criatividade:");

        labelCreativity.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(labelCreativityDONTEDIT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSF)
                            .addComponent(labelFP)
                            .addComponent(labelCF)
                            .addComponent(labelGP)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(labelImage)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(labelFARM))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(labelCreativity)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeedFertilizer)
                            .addComponent(btnFoodProduction)
                            .addComponent(btnCocoFertilizer)
                            .addComponent(btnGreatProduction))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImage)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(labelFARM)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreativityDONTEDIT)
                    .addComponent(labelCreativity))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFP)
                    .addComponent(btnFoodProduction))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSF)
                    .addComponent(btnSeedFertilizer))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCF)
                    .addComponent(btnCocoFertilizer))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGP)
                    .addComponent(btnGreatProduction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LojaVirtual(gameData).setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFoodProductionActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.FOOD_PRODUCTION)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.FOOD_PRODUCTION));
    		BuildingTools.unlockUpgrade(BuildingTools.FARM, Farm.FOOD_PRODUCTION);
    		
    		btnFoodProduction.setText("Unlocked");
    		btnFoodProduction.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voc� n�o est� inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnSeedFertilizerActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.SEED_FERTILIZER)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.SEED_FERTILIZER));
    		BuildingTools.unlockUpgrade(BuildingTools.FARM, Farm.SEED_FERTILIZER);
    		
    		btnSeedFertilizer.setText("Unlocked");
    		btnSeedFertilizer.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voc� n�o est� inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnCocoFertilizerActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.COCO_FERTILIZER)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.COCO_FERTILIZER));
    		BuildingTools.unlockUpgrade(BuildingTools.FARM, Farm.COCO_FERTILIZER);
    		
    		btnCocoFertilizer.setText("Unlocked");
    		btnCocoFertilizer.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voc� n�o est� inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnGreatProductionActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.GREAT_PRODUCTION)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.FARM, Farm.GREAT_PRODUCTION));
    		BuildingTools.unlockUpgrade(BuildingTools.FARM, Farm.GREAT_PRODUCTION);
    		
    		btnGreatProduction.setText("Unlocked");
    		btnGreatProduction.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voc� n�o est� inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCocoFertilizer;
    private javax.swing.JButton btnFoodProduction;
    private javax.swing.JButton btnGreatProduction;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSeedFertilizer;
    private javax.swing.JLabel labelCF;
    private javax.swing.JLabel labelCreativity;
    private javax.swing.JLabel labelCreativityDONTEDIT;
    private javax.swing.JLabel labelFARM;
    private javax.swing.JLabel labelFP;
    private javax.swing.JLabel labelGP;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelSF;
    // End of variables declaration//GEN-END:variables
}
