/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

/**
 *
 * @author Fer
 */
public class LojaVirtual extends javax.swing.JFrame {

    /**
     * Creates new form LojaVirtual
     */
    public LojaVirtual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnFarmUpgrade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFarmBuy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLabBuy = new javax.swing.JButton();
        btnTempleBuy = new javax.swing.JButton();
        btnMineBuy = new javax.swing.JButton();
        btnLabUpgrade = new javax.swing.JButton();
        btnTempleUpgrade = new javax.swing.JButton();
        btnMineUpgrade = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAboutLab = new javax.swing.JButton();
        btnAboutFarm = new javax.swing.JButton();
        btnAboutTemple = new javax.swing.JButton();
        btnAboutMine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        jLabel1.setText("Loja Virtual");

        jButton1.setText("Finalizar Compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnFarmUpgrade.setText("Upgrades");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Farm.png"))); // NOI18N
        jLabel2.setText("Fazenda");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lab2.png"))); // NOI18N
        jLabel3.setText("Laboratório");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Temple.png"))); // NOI18N
        jLabel4.setText("Templo");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mine.png"))); // NOI18N
        jLabel5.setText("Mina");

        btnFarmBuy.setText("Comprar");

        jLabel6.setText("--------------");

        jLabel7.setText("--------------");

        jLabel8.setText("--------------");

        jLabel9.setText("--------------");

        jLabel10.setText("$400,00");

        jLabel11.setText("$400,00");

        jLabel12.setText("$400,00");

        jLabel13.setText("$400,00");

        btnLabBuy.setText("Comprar");

        btnTempleBuy.setText("Comprar");

        btnMineBuy.setText("Comprar");

        btnLabUpgrade.setText("Upgrades");

        btnTempleUpgrade.setText("Upgrades");

        btnMineUpgrade.setText("Upgrades");

        jLabel14.setText("Money:");

        jLabel15.setText("$500,00");

        btnAboutLab.setText("Info");
        btnAboutLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutLabActionPerformed(evt);
            }
        });

        btnAboutFarm.setText("Info");
        btnAboutFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutFarmActionPerformed(evt);
            }
        });

        btnAboutTemple.setText("Info");
        btnAboutTemple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutTempleActionPerformed(evt);
            }
        });

        btnAboutMine.setText("Info");
        btnAboutMine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutMineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnAboutFarm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAboutTemple)
                                            .addComponent(btnAboutLab)
                                            .addComponent(btnAboutMine))
                                        .addGap(6, 6, 6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFarmBuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnFarmUpgrade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLabBuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnLabUpgrade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTempleBuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnTempleUpgrade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMineBuy)
                        .addGap(18, 18, 18)
                        .addComponent(btnMineUpgrade)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFarmUpgrade)
                    .addComponent(jLabel2)
                    .addComponent(btnFarmBuy)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(btnAboutFarm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(btnLabBuy)
                    .addComponent(btnLabUpgrade)
                    .addComponent(btnAboutLab))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(btnTempleBuy)
                    .addComponent(btnTempleUpgrade)
                    .addComponent(btnAboutTemple))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(btnMineBuy)
                    .addComponent(btnMineUpgrade)
                    .addComponent(btnAboutMine))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAboutLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutLabActionPerformed
        // TODO add your handling code here:
        new InfoLab().setVisible(true);
    }//GEN-LAST:event_btnAboutLabActionPerformed

    private void btnAboutFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutFarmActionPerformed
        // TODO add your handling code here:
        new InfoFarm().setVisible(true);
    }//GEN-LAST:event_btnAboutFarmActionPerformed

    private void btnAboutTempleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutTempleActionPerformed
        // TODO add your handling code here:
          new InfoTemple().setVisible(true);
    }//GEN-LAST:event_btnAboutTempleActionPerformed

    private void btnAboutMineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutMineActionPerformed
        // TODO add your handling code here:
          new InfoMine().setVisible(true);
    }//GEN-LAST:event_btnAboutMineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaVirtual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutFarm;
    private javax.swing.JButton btnAboutLab;
    private javax.swing.JButton btnAboutMine;
    private javax.swing.JButton btnAboutTemple;
    private javax.swing.JButton btnFarmBuy;
    private javax.swing.JButton btnFarmUpgrade;
    private javax.swing.JButton btnLabBuy;
    private javax.swing.JButton btnLabUpgrade;
    private javax.swing.JButton btnMineBuy;
    private javax.swing.JButton btnMineUpgrade;
    private javax.swing.JButton btnTempleBuy;
    private javax.swing.JButton btnTempleUpgrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
