/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;

import buildings.Temple;
import core.BuildingTools;
import core.GameManager;
import core.ResourceManager;

/**
 *
 * @author Fer
 */
public class TempleUpdate extends javax.swing.JFrame {
    GameManager gameData;
    /**
     * Creates new form TempleMelhoria
     */
    public TempleUpdate(GameManager gameData) {
        this.setResizable(false);
        //this.setLocationRelativeTo(null);
        this.gameData = gameData;
        initComponents();
        labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
        
        if (BuildingTools.getUpgrade(BuildingTools.TEMPLE, Temple.GEM_PRODUCTION)){
    		btnGemProduction.setText("Liberado");
    		btnGemProduction.setEnabled(false);
    	} else {
    		btnGemProduction.setText("Bloqueado: " + BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GEM_PRODUCTION));
            btnGemProduction.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGemProductionActionPerformed(evt);
                }
            });
    	}
        
        if (BuildingTools.getUpgrade(BuildingTools.TEMPLE, Temple.PERL_RITUAL)){
    		btnPerlR.setText("Liberado");
    		btnPerlR.setEnabled(false);
    	} else {
    		btnPerlR.setText("Bloqueado: " + BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PERL_RITUAL));
            btnPerlR.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPerlRActionPerformed(evt);
                }
            });
    	}
        
        if (BuildingTools.getUpgrade(BuildingTools.TEMPLE, Temple.PYRAMID_RITUAL)){
    		btnPyR.setText("Liberado");
    		btnPyR.setEnabled(false);
    	} else {
    		btnPyR.setText("Bloqueado: " + BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PYRAMID_RITUAL));
            btnPyR.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnPyRActionPerformed(evt);
                }
            });
    	}
        
        if (BuildingTools.getUpgrade(BuildingTools.TEMPLE, Temple.GREAT_RITUAL)){
    		btnGreatRitual.setText("Liberado");
    		btnGreatRitual.setEnabled(false);
    	} else {
    		btnGreatRitual.setText("Bloqueado: " + BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GREAT_RITUAL));
            btnGreatRitual.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGreatRitualActionPerformed(evt);
                }
            });
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labelCreativity = new javax.swing.JLabel();
        btnGemProduction = new javax.swing.JButton();
        btnPerlR = new javax.swing.JButton();
        btnPyR = new javax.swing.JButton();
        btnGreatRitual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TempleBig.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bangla Sangam MN", 0, 24)); // NOI18N
        jLabel2.setText("TEMPLO");

        jLabel3.setText("Gem Production:");

        jLabel4.setText("Perl Ritual:");

        jLabel5.setText("Pyramid Ritual:");

        jLabel6.setText("Grande Ritual:");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel11.setText("Criatividade:");

        labelCreativity.setText("0");

        btnGemProduction.setText("Bloqueado: 30");

        btnPerlR.setText("Bloqueado: 30");

        btnPyR.setText("Bloqueado: 30");

        btnGreatRitual.setText("Bloqueado: 30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(40, 40, 40)
                                .addComponent(labelCreativity))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGreatRitual))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnPyR, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnPerlR, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnGemProduction, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelCreativity))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGemProduction)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnPerlR))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnPyR))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGreatRitual)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
         this.dispose();
         new MyClasses(gameData).setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnGemProductionActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GEM_PRODUCTION)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GEM_PRODUCTION));
    		BuildingTools.unlockUpgrade(BuildingTools.TEMPLE, Temple.GEM_PRODUCTION);
    		
    		btnGemProduction.setText("Liberado");
    		btnGemProduction.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voce nao esta inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnPerlRActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PERL_RITUAL)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PERL_RITUAL));
    		BuildingTools.unlockUpgrade(BuildingTools.TEMPLE, Temple.PERL_RITUAL);
    		
    		btnPerlR.setText("Liberado");
    		btnPerlR.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voce nao esta inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnPyRActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PYRAMID_RITUAL)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.PYRAMID_RITUAL));
    		BuildingTools.unlockUpgrade(BuildingTools.TEMPLE, Temple.PYRAMID_RITUAL);
    		
    		btnPyR.setText("Liberado");
    		btnPyR.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voce nao esta inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }
    
    private void btnGreatRitualActionPerformed(java.awt.event.ActionEvent evt) {
    	if (gameData.resources.getCreativity() >= BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GREAT_RITUAL)){
    		gameData.resources.updateCreativity(-BuildingTools.getUpgradeCost(BuildingTools.TEMPLE, Temple.GREAT_RITUAL));
    		BuildingTools.unlockUpgrade(BuildingTools.TEMPLE, Temple.GREAT_RITUAL);
    		
    		btnGreatRitual.setText("Liberado");
    		btnGreatRitual.setEnabled(false);
    		
    		labelCreativity.setText(Integer.toString(gameData.resources.getCreativity()));
    	} else {
    		JOptionPane.showMessageDialog(null, "Voce nao esta inspirado o suficiente para entender como isso funciona... Busque mais criatividade!", "Bloqueio Criativo",
    				JOptionPane.ERROR_MESSAGE);
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGemProduction;
    private javax.swing.JButton btnGreatRitual;
    private javax.swing.JButton btnPerlR;
    private javax.swing.JButton btnPyR;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelCreativity;
    // End of variables declaration//GEN-END:variables
}
